### PR TITLE
Support of SLURM

### LINKED ISSUE #24: Epic - add slurm
- [x] #587
- [x] #588
- [x] #589
- [x] #590
- [x] #591
- [x] #592
- [x] #593
- [ ] #594

### LINKED ISSUE #643: implement log rotation for SLURM
see instructions on https://wiki.fysik.dtu.dk/niflheim/Slurm_installation#log-file-rotation

### LINKED ISSUE #649: hostnames not renamed correctly for SLURM
image

Versions : 
* CC 8.2.1
* Slurm project 2.5.0
* az-hop 1.0.11
* branch feature-slurm

### LINKED ISSUE #656: SLURM job is not starting
Version : 1.0.10
SLURM : 20.11.7
Cycleclud-slurm : 2.50
CycleCloud : 8.2.1

`srun --nodes=1 --partition=execute hostname`

Node is created, however job never start
/var/log/slurm/slurmd.log contains 
```
[2021-12-02T15:17:11.690] debug:  auth/munge: slurm_auth_create: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory (retrying ...)
[2021-12-02T15:17:11.790] debug:  auth/munge: slurm_auth_create: Munge encode failed: Failed to access "/var/run/munge/munge.socket.2": No such file or directory (retrying ...)
[2021-12-02T15:17:11.893] debug:  _handle_node_reg_resp: slurmctld sent back 8 TRES.

...
[2021-12-02T16:59:41.539] debug:  slurm_recv_timeout at 0 of 4, recv zero bytes
[2021-12-02T16:59:41.539] error: slurm_receive_msg_and_forward: Zero Bytes were transmitted or received
[2021-12-02T16:59:41.550] error: service_connection: slurm_receive_msg: Zero Bytes were transmitted or received
[2021-12-02T16:59:46.544] debug:  slurm_recv_timeout at 227 of 369295616, recv zero bytes
```

Similar issues https://www.mail-archive.com/slurm-users@lists.schedmd.com/msg07947.html

### LINKED ISSUE #660: slurmctld failing to start on a fresh new deployment
manually restarting the slurmctld service works

### PR DESCRIPTION
**Pull request by xpillons**
- Support of SLURM 20.11.7
- New CycleCloud template added for SLURM using the 2.5.0 cyclecloud-slurm project
- Accounting managed mySQL database provisionned, this is optional. Turned on by default, false if missing
- Configure log rotation to rotate on a daily basis keeping 7 days of logs

close #24 
close #656 
close #649 
close #660 
close #643

### CODE REVIEW

**Review by hmeiland — APPROVED** [review]

**Comment by vgamayunov** [comment]
We still need to rename the queues to avoid underscores in the hostnames

**Comment by xpillons** [comment]
> We still need to rename the queues to avoid underscores in the hostnames

I will do it in a separate branch and PR in order to track it as it will change the documentation as well as tutorials

**Comment by themorey** [comment]
note that Slurm project 2.5.1 was pushed to fix a name resolution issue in 2.5.0

**Comment by xpillons** [comment]
Yes, but the project cyclecloud/slurm:2.5.1 has not been pushed yet in the public cycle lockers

**Pull request merged**
