### PR TITLE
Use external auth module - Extra Dependency

### PR DESCRIPTION
**Pull request by pddro-Vestas**
Add additional dependency (pwauth) for mod_authnz_external

### CODE REVIEW

**Comment by xpillons** [comment]
this update didn't works either with AD or without. Still Apache not willing to start

**Comment by pddro-Vestas** [comment]
Could it be that /etc/httpd/conf.modules.d/10-authnz_external.conf is commented? I tested in my setup (Alma 8.7) and it is active by default. Can you share apache / httpd logs?

**Comment by xpillons** [comment]
I'm investigating at the moment

**Comment by xpillons** [comment]
got it to work, I add to update more things in the apache config file generated by OOD. please check PR #1772

**Comment by pddro-Vestas** [comment]
Glad you found the issue :) Maybe I did not see that issue because I am using OpenID connect auth for the OOD Portal.

**Comment by xpillons** [comment]
I will close this PR as I created a specific branch for testing, and it's now in #1772

**Pull request closed without merging**
