### PR TITLE
Add Terraform guard

### PR DESCRIPTION
**Pull request by matt-chan**
Hi Xavier,

We added a terraform guard after I accidentally blew away a live deployment (for the third time...).

If you like it, please feel free to merge it.

Matt
(cc @ltalirz)

### CODE REVIEW

**Comment by xpillons** [comment]
why did it blew away your current deployment ? terraform state is there to maintain the current view of what has been deployed. So unless you change your resource group name which then is related to another issue there is no need to confirm in my opinion. In any case before doing a new deployment you can run with the "-a plan" option to validate what will be done.
Having a manual entry will avoid automation thru pipelines, especially with the option to use ANF with SMB as it's a 2 stage deployment. Let's understand why you had this and fix it.

**Comment by ltalirz** [comment]
> So unless you change your resource group name which then is related to another issue

That was itr

**Comment by ltalirz** [comment]
It would also already help to just document how to clean an existing git repo without having to go via a git server - [something like](https://stackoverflow.com/questions/61212/how-to-remove-local-untracked-files-from-the-current-git-working-tree) `git clean -f`

**Comment by xpillons** [comment]
> > So unless you change your resource group name which then is related to another issue
> 
> That was it
> 
> I guess this goes to the intent behind changing values in the configuration. Changing the name of the resource group, at least in our case, indicated that we wanted to do a fresh deployment rather than to change the name of the resource group of a previous deployment.
> 
> I think this is a common use case, and a guard specifically for this case (limited to changes in resource group name) could make sense. In this case, the operator will typically want to delete all temporary files and start from scratch.

in that case removing the tfstate would be enough. as the tfstate contains the resource group, then it should be possible to compare the name in the config file and in the tfstate and delete the tfstate if different.

**Comment by xpillons** [comment]
please check if this fix https://github.com/Azure/az-hop/blob/fix/948/build.sh can solve your problem

**Comment by matt-chan** [comment]
Hi @xpillons , 

Yep it looks good to me! The only other thing I'd be wary of is that the playbooks will have their .ok files, but that's not going to break anything already in prod.

Thanks!

**Pull request closed without merging**
