### PR TITLE
retry modprobe lustre and fail on error (client)

### PR DESCRIPTION
**Pull request by vgamayunov**

### CODE REVIEW

**Review by xpillons — COMMENTED** [review]
Does this works even if the lustre client is not installed in the image ? in that case you want to silently failed.

**Comment by edwardsp** [comment]
Yes, I was going to ask the same thing.  It's good to retry but we might
want to just `exit 0` on failure.

**Comment by vgamayunov** [comment]
I agree, `exit 0` is more robust in case we don't want lustre on a vm.
Another option is to check is the module is installed, something like `modinfo lustre >&/dev/null || exit 0` then `exit 1` if failed.
I prefer first option.

**Comment by vgamayunov** [comment]
updated the script to exit without error + some refactoring. 5 retries with 5 second delay.

**Review by xpillons — APPROVED** [review]

**Comment by xpillons** [comment]
@edwardsp @vgamayunov can you please review the latest updates ?

**Comment by vgamayunov** [comment]
@xpillons can you think of a scenario when lustre module is in the image, but we wait the error to be silent?
If not, then I think this is good now.

**Comment by xpillons** [comment]
@vgamayunov it's not the case today. so I will proceed with the merge. However we shoud think about making Lustre optional

**Pull request merged**
