### PR TITLE
add rstudio app

### PR DESCRIPTION
**Pull request by JingchaoZhang**
add rstudio app to azhop

### CODE REVIEW

**Comment by xpillons** [comment]
Please add configuration entries in these files :
- config.tpl.yml
- docs/deploy/index.md
- .github/workflows/configs/integration.yml

Update schema in config.schema.json

**Review by xpillons — CHANGES_REQUESTED** [review]
please review readme.md as it doesn't applied to this context entirely

**Review by xpillons — APPROVED** [review]

**Comment by JingchaoZhang** [comment]
rstudio entries have been added to the following files:
- config.tpl.yml
- docs/deploy/index.md
- .github/workflows/configs/integration.yml

I also found bc_jupyter entries in the following files. Do we need to add bc_rstudio in them? 
- deploy/resources/azhop-config-templates/config.yml.j2
- docs/apps/index.md
- playbooks/roles/ood-applications/defaults/main.yml

**Review by xpillons — APPROVED** [review]

**Comment by xpillons** [comment]
we missed adding it in `playbooks/roles/ood-applications/defaults/main.yml`
I've pushed an update in main

**Pull request merged**
