### PR TITLE
New toolchain install script

### PR DESCRIPTION
**Pull request by yosoyjay**
This pull request aims to simplify the installation of the dependencies required to deploy an az-hop instance by migrating the installation of all dependencies to a new script `install_dependencies.sh` that:

- Optionally installs a miniconda environment to allow isolated installation and installation on older OSes (e.g. CentOS7)
- Installs Ansible and dependencies via `pip` using a `requirements.txt` file
- Installs Ansible collections using a `requirements.yaml` file
- Bootstraps the other az-hop dependencies using a new `azhop-dependencies.yml` playbook with support for Ubuntu, CentOS, and macOS
- Ensures the required OnDemand git submodule is present

The changes have been tested and work on:

- Ubuntu 20.04, 22.04
- CentOS 7.9
- macOS 13

Known rough edges:

- Requires sudo on Linux and could result in awkward permissions for miniconda if installed
- It might be better to force installation of Ansible etc. in a virtual environment
- Install for Ubuntu and CentOS on aarm64 fail due to packaging issues with AzureCLI
- No `set -x` in `install_dependencies.sh` 
- Logging could be improved

Open issues:
- Docs need to be updated
- Some deploy scripts likely need to be updated (e.g. `deploy/purebicep/install.sh`) etc.

### CODE REVIEW

**Comment by xpillons** [comment]
can you please update the install.sh so it will call the dependencies one ? You have remove the call to pre_reqs.sh so it needs to be udpated.
Also maybe this should added when installing the toolset toolset/scripts https://azure.github.io/az-hop/deploy/index#configure-the-toolchain.  These scripts are used to setup your local env and to build the container used by pipelines

**Comment by yosoyjay** [comment]
The call to `ansible_prereqs.sh` was removed in [`install.sh`](https://github.com/Azure/az-hop/blob/b269b2b591ab7f842bfccc8aea79a6d967d0a888/install.sh#LL94-LL96).  I do see a call to `deploy/pre-reqs.sh` which only installs `yq`in docs/tutorials/quickstart.md` and I believe that's the only place where it is used.  Is that what you are referring to?

In regards to adding `install_dependencies.sh` to `install.sh`, would it be more appropriate for the use cases you envision to always install conda or expose that option as a CLI argument in `install.sh`?

Other changes I believe would be required after moving `install_dependencies.sh` to `toolset/scripts`:
- `update_selfhost.yml`
- `deploy/purebicep`
- `docs/deploy/index.md`
- `toolset/Dockerfile` 

Am I missing anything?  @edwardsp any feedback?

**Comment by xpillons** [comment]
@yosoyjay I've moved everything under toolset/scripts/install.sh with companions files.
This will ensure a smooth transition and no need to update anything else.
the submodule init has been moved out from the toolset as it's not appropriate in this location when building the container.

**Review by xpillons — APPROVED** [review]

**Comment by yosoyjay** [comment]
@xpillons A couple of questions/comments:
- Do the current docs reflect the expected deployment processes?
- There's is now dead code in [`toolset/scripts/install.sh`](https://github.com/Azure/az-hop/blob/66ae04d8c842b16c5db9675f20f92b8b99475186/toolset/scripts/install.sh#LL14-L27C5) that should be removed if deployment is always using _conda_.  Is that the case?

**Comment by xpillons** [comment]
yes code has been cleanup, the current doc doesn't reflect it yet, but calling activate is embedded so users shouldn't worry about it. I'm trying to make github pipelines to work, so expect few more fixes in other branches

**Pull request merged**
