### PR TITLE
renamed vnet peerings, added vnet_allow_gateway setting

### PR DESCRIPTION
**Pull request by vgamayunov**
* renamed vnet peerings to "rg_name-vnet_name" to allow more than one peering with one RG
* added vnet_allow_gateway config setting to be able to peer with vnet without gateway

### CODE REVIEW

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree company="microsoft"
________________________________

**Review by xpillons — APPROVED** [review]

**Comment by vgamayunov** [comment]
> @vgamayunov please read the following Contributor License Agreement(CLA). If you agree with the CLA, please reply with the following information.
> 
> ```
> @microsoft-github-policy-service agree [company="{your company}"]
> ```
> 
> > Options:
> > 
> > * (default - no company specified) I have sole ownership of intellectual property rights to my Submissions and I am not making Submissions in the course of work for my employer.
> > * (when company given) I am making Submissions in the course of work for my employer (or my employer has intellectual property rights in my Submissions by contract or applicable law). I have permission from my employer to make Submissions and enter into this Agreement on behalf of my employer. By signing below, the defined term “You” includes me and my employer.
> 
> Contributor License Agreement

@microsoft-github-policy-service agree

> 

@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree company="Microsoft"

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service help

**Comment by vgamayunov** [comment]
@microsoft-github-policy-service agree company="microsoft"

**Pull request merged**
